# Documentation:
#  https://www.keycloak.org/server/containers
#  https://github.com/keycloak/keycloak/issues/17438

ARG KEYCLOAK_VERSION
FROM registry.access.redhat.com/ubi9 AS ubi-micro-build

RUN mkdir -p /mnt/rootfs \
    && dnf remove -y subscription-manager \
    && dnf install --installroot /mnt/rootfs curl jq \
           --releasever 9 \
           --setopt install_weak_deps=false \
           --nodocs -y \
    && dnf --installroot /mnt/rootfs clean all \
    && rpm --root /mnt/rootfs -e --nodeps setup

FROM quay.io/keycloak/keycloak:$KEYCLOAK_VERSION

USER root
COPY --from=ubi-micro-build /mnt/rootfs /

COPY ./.ci/deploy/localenv/data/keycloak/keycloak_functions.sh /keycloak_functions.sh
COPY ./.ci/deploy/localenv/data/keycloak/provision.sh /provision.sh

USER keycloak
RUN curl --version
RUN jq --version
RUN echo 'kcadm() { local cmd="$1" ; shift ; "$KCADM_PATH" "$cmd" --config /tmp/kcadm.config "$@" ; }' >> /opt/keycloak/.bashrc
RUN echo 'kcauth() { kcadm config credentials config --server "$KEYCLOAK_URL" --realm master --user "$KC_BOOTSTRAP_ADMIN_USERNAME" --password "$KC_BOOTSTRAP_ADMIN_PASSWORD" ; }' >> /opt/keycloak/.bashrc

ENTRYPOINT [ "/provision.sh" ]
